version: 2
registries:
  github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/technoir42/gradle-convention-plugins
    username: "${{ secrets.MAVEN_USERNAME }}"
    password: "${{ secrets.MAVEN_PASSWORD }}"

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - github-packages
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
