version: 2
updates:
  - package-ecosystem: "gradle"
    cooldown:
      exclude:
        - "io.technoirlab:*"
        - "io.technoirlab.*:*"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
