formatting:
  ArgumentListWrapping:
    maxLineLength: 140
  ContextReceiverMapping:
    maxLineLength: 140
  FunctionReturnTypeSpacing:
    maxLineLength: 140
  FunctionSignature:
    maxLineLength: 140
  MaximumLineLength:
    maxLineLength: 140
  ParameterListWrapping:
    maxLineLength: 140
  ParameterWrapping:
    maxLineLength: 140
  PropertyWrapping:
    maxLineLength: 140
  Wrapping:
    maxLineLength: 140

naming:
  FunctionNaming:
    ignoreAnnotated:
      - org.junit.jupiter.api.Test

style:
  ForbiddenComment:
    active: false
  MaxLineLength:
    active: false
