name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # required for dependency graph submission

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          dependency-graph: generate-and-submit

      - name: Publish to local Maven repository
        run: |
          ./gradlew publishToMavenLocal \
          -Pgpr.user=${{ github.repository_owner }} \
          -Pgpr.token=${{ secrets.GITHUB_TOKEN }}

      - name: Build with Gradle
        run: |
          ./gradlew build \
          --scan \
          -Pgpr.user=${{ github.repository_owner }} \
          -Pgpr.token=${{ secrets.GITHUB_TOKEN }}

  actions-lint:
    name: Lint workflows
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint workflows
        uses: reviewdog/action-actionlint@v1
        with:
          level: warning
          fail_level: error
