name: Publish

on:
  push:
    tags: [ "*" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: >
          ./gradlew publish
          --no-configuration-cache
          -Pgpr.user=${{ github.repository_owner }}
          -Pgpr.token=${{ secrets.GITHUB_TOKEN }}
          -Pproject.version=${{ github.ref_name }}
          -Ppublish.url=https://maven.pkg.github.com/technoir-lab/convention-plugins
          -Ppublish.username=${{ secrets.GPR_DEPLOY_USER }}
          -Ppublish.password=${{ secrets.GPR_DEPLOY_TOKEN }}
