name: Publish

on:
  push:
    tags: [ "*" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew publish \
          --no-configuration-cache \
          --scan \
          -Pgpr.user=${{ github.repository_owner }} \
          -Pgpr.token=${{ secrets.GITHUB_TOKEN }} \
          -Pproject.version=${{ github.ref_name }} \
          -Ppublish.url=https://maven.pkg.github.com/technoir-lab/convention-plugins \
          -Ppublish.username=${{ secrets.GPR_DEPLOY_USER }} \
          -Ppublish.password=${{ secrets.GPR_DEPLOY_TOKEN }}

  documentation:
    name: Documentation
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Generate documentation
        run: |
          ./gradlew :dokkaGenerate \
          --scan \
          -Pgpr.user=${{ github.repository_owner }} \
          -Pgpr.token=${{ secrets.GITHUB_TOKEN }} \
          -Pproject.version=${{ github.ref_name }}

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokka/html

      - name: Deploy documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
